version: '3.8'

services:
    portal:
        container_name: portal
        hostname: portal
        build:
            context: ../unifametro_frameworkweb
            dockerfile: Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/unifametro_frameworkweb
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - banco

    banco:
        container_name: banco
        hostname: banco
        image: postgres:14.6-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 19000:5432
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=pass.2023
            - POSTGRES_DB=argovinos
            - TZ=GMT-3

volumes:
    postgres_data:
